### ISSUE TITLE
[SS 3.3] Error from entwine

### ISSUE THREAD

**Issue by gregsmirnov** [silverstripe/silverstripe-tagfield#74]
Steps to reproduce:
1. Create PageTag class and add m-m relation to Page as described in Readme
2. Open CMS to edit existing page in Chrome browser (used v48)
3. Open Developer tools
4. Click Save button
5. Observe exception in the JS console

``` js
jquery.entwine-dist.js?m=1455273235:888 Uncaught exception TypeError: Cannot read property 'apply' of undefined(…) in onunmatch on
 <select name=​"Tags[]​" class=​"tag ss-tag-field select2-hidden-accessible" id=​"Form_EditForm_Tags" multiple style=​"display:​ inline-block;​" tabindex=​"-1" aria-hidden=​"true">​</select>​
jquery.entwine-dist.js?m=1455273235:891 Stack Trace:
TypeError: Cannot read property 'apply' of undefined
    at HTMLSelectElement.one [as f] (http://example.com/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1455273235:1011:37)
    at jQuerySub.$.extend._super (http://example.com/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1455273235:1153:13)
    at jQuerySub.$.entwine.onunmatch (http://example.com/framework/admin/javascript/LeftAndMain.js?m=1455273230:1286:10)
    at Array.proxy [as onunmatchproxy] (http://example.com/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1455273235:1867:23)
    at HTMLDocument.<anonymous> (http://example.com/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1455273235:2043:16)
    at HTMLDocument.jQuery.event.dispatch (http://example.com/framework/thirdparty/jquery/jquery.js?m=1455273235:3332:9)
    at HTMLDocument.elemData.handle.eventHandle (http://example.com/framework/thirdparty/jquery/jquery.js?m=1455273235:2941:28)
    at Object.jQuery.event.trigger (http://example.com/framework/thirdparty/jquery/jquery.js?m=1455273235:3210:12)
    at jQuery.fn.extend.triggerHandler (http://example.com/framework/thirdparty/jquery/jquery.js?m=1455273235:3874:24)
    at Base.extend.triggerEvent (http://example.com/framework/thirdparty/jquery-entwine/dist/jquery.entwine-dist.js?m=1455273235:1351:16)
```

There are no difference whether page tags exist or not.
Tested with Chrome v48, FF v43, v44

**Comment by tractorcow** [comment]
ouch, that looks like a tough problem. Also all of the stacktrace is in core methods, so it's hard to see what part of the tagfield code could be causing it. =/

**Comment by jakmax76** [comment]
any news about this issue?
thanks

**Comment by tractorcow** [comment]
News is that no one has submitted a patch for it yet. :D I'd review if someone were to investigate and PR.

**Comment by jcop007** [comment]
We're also experiencing the same issue.  I had a quick look and can see that tags are not being save to database.  Will investigate further if time permits.

**Comment by jcop007** [comment]
The example for relational tag on this page doesn't work.  
http://addons.silverstripe.org/add-ons/silverstripe/tagfield

I found the example on this page works:
https://github.com/silverstripe/silverstripe-tagfield

The problem is with the form field Formfield Instanciation line:
$tagField = new TagField('RelationTags', null, null, 'Article')

**Comment by dhensby** [comment]
@jcop007 would you be willing to provide a patch?

**Comment by jcop007** [comment]
Yes, can do.

Regards,
Jonathan.

**Comment by sanderha** [comment]
Has this been fixed?

**Comment by tractorcow** [comment]
@jcop007 I know it's been a while but did you still have a patch you could provide to us? Thank you. ;D

**Comment by jcop007** [comment]
@tractorcow I think the problem is just that the example on http://addons.silverstripe.org/add-ons/silverstripe/tagfield doesn't work.  It's got nulls in the two last parameters where is should have data arrays.  The examples on github are fine.   How does that add-ons article get updated?

**Comment by tractorcow** [comment]
That might be a question for @robbieaverill

**Comment by robbieaverill** [comment]
It should be automated but I’ll check it tomorrow morning

**Comment by robbieaverill** [comment]
Wow, that readme is very out of date! Raised at https://github.com/silverstripe/addons.silverstripe.org/issues/174

**Comment by carlwells** [comment]
I'm not convinced that is only a documentation issue.
I've just installed SS 3.6 and I'm using Tagfield 1.3.2 and I'm experiencing this issue.
Tagfield has been downloaded from github & addons.silverstripe and I'm getting the error on both installs.

Tagfield readme requirements are SilverStripe 3.1 or newer

`jquery.entwine-dist.js?m=1498564096:888 Uncaught exception TypeError: Cannot read property 'apply' of undefined
    at HTMLSelectElement.one [as f] (jquery.entwine-dist.js?m=1498564096:1011)
    at init._super (jquery.entwine-dist.js?m=1498564096:1153)
    at init.onunmatch (LeftAndMain.js?m=1498564096:1289)
    at Array.proxy [as onunmatchproxy] (jquery.entwine-dist.js?m=1498564096:1867)
    at HTMLDocument.<anonymous> (jquery.entwine-dist.js?m=1498564096:2043)
    at HTMLDocument.dispatch (jquery.js?m=1498564096:3332)
    at HTMLDocument.eventHandle (jquery.js?m=1498564096:2941)
    at Object.trigger (jquery.js?m=1498564096:3210)
    at init.triggerHandler (jquery.js?m=1498564096:3874)
    at Kls.triggerEvent (jquery.entwine-dist.js?m=1498564096:1351) in onunmatch on <select name=​"Tags[]​" class=​"tag ss-tag-field select2-hidden-accessible" id=​"Form_EditForm_Tags" multiple data-ss-tag-field-suggest-url=​"admin/​pages/​edit/​EditForm/​155/​field/​Tags/​suggest" data-can-create=​"1" style=​"display:​ inline-block;​" tabindex=​"-1" aria-hidden=​"true">​<option value=​"1">​Testing​</option>​<option value=​"2">​Testing Two</option>​</select>​
`

**Comment by carlwells** [comment]
If it helps I've narrowed my issue down to entwine looking to call onunmatch from an array of methods.
I believe these are set in the javascript files for the relevant includes.
In this case the Tagfield.js file has an onmatch function but no onunmatch function.
Adding an onunmatch function removed the error but I have no idea of any side-effects to doing that as I'm not familiar enough with the code.
``
onunmatch: function () {
return false;
}
``

**Comment by jcop007** [comment]
@carlwells We use the same version of SS & Tagfield without any issues.  Have you tried dumping the 3 & 4th parameters you are passing to the new tagfield to check that they aren't null?  A null value there will cause the issue.   $field = TagField::create(
	'BlogTags',
	'Blog Tags',
	BlogTag::get(),
	$this->BlogTags()
)

**Comment by carlwells** [comment]
@jcop007 That's really odd then. Both values are not null but I still see the error. I'll see if I can isolate it. Thanks.

**Comment by svenV88** [comment]
Still having the same issue in **SS 4.2.1**. It only happens after publishing the post/page, if I do a refresh there is no error.
It doesn't cause any problems with the tagfield itself, but because of this error the SimpleMDEEditor doesn't render.

Currently using version **2.1.0** of this package.

**CMSfields:**
```php
/**
   * CMS Fields
   * @return FieldList
   */
  public function getCMSFields()
  {
    $fields = parent::getCMSFields();
    $fields->replaceField('Content', SimpleMDEEditor::create('Content'));
    $fields->addFieldsToTab(
      'Root.Main',
      array(
        $tagfield = TagField::create('Tags', 'Tags', Tag::get(), $this->Tags()),
        $categoriesfield = TreeMultiselectField::create('Categories', 'Categories', Category::class),
        HiddenField::create('Author', 'Auther', Security::getCurrentUser()->ID)
      ),
      'Metadata'
    );

    $tagfield->setShouldLazyLoad(true);
    $tagfield->setCanCreate(true);

    return $fields;
  }
```

**error:**
```javascript
vendor.js?m=1542703029:formatted:72790 Uncaught exception TypeError: Cannot read property 'apply' of undefined
    at HTMLSelectElement.s [as f] (vendor.js?m=1542703029:formatted:72873)
    at init._super (vendor.js?m=1542703029:formatted:72948)
    at init.onunmatch (bundle.js?m=1542703029:1)
    at Array.u [as onunmatchproxy] (vendor.js?m=1542703029:formatted:73380)
    at HTMLDocument.<anonymous> (vendor.js?m=1542703029:formatted:73446)
    at HTMLDocument.dispatch (eval at e.exports (vendor.js?m=1542703029:formatted:68673), <anonymous>:3332:9)
    at HTMLDocument.eventHandle (eval at e.exports (vendor.js?m=1542703029:formatted:68673), <anonymous>:2941:28)
    at Object.trigger (eval at e.exports (vendor.js?m=1542703029:formatted:68673), <anonymous>:3210:12)
    at init.triggerHandler (eval at e.exports (vendor.js?m=1542703029:formatted:68673), <anonymous>:3874:24)
    at o.triggerEvent (vendor.js?m=1542703029:formatted:73061) in onunmatch on 
```

**Comment by robbieaverill** [comment]
@svenV88 the upcoming tagfield 2.2.1 release should fix this for you. Can you try using `2.2.x-dev` and see if it fixes your issue?

**Comment by svenV88** [comment]
@robbieaverill Just left the office when you replied. Started to try it this morning and had some difficulties upgrading to 4.3 as I was using 4.2.1. which wasn't in range with the dependencies of 2.2.x-dev (fortunately everything is working now). Unfortunately I still get a warning at the same moment as described before. This time it is a different one though:

```javascript
Uncaught exception Error: Injector.get(): Component TagField does not exist
    at Object.get (bundle.js?m=1544431027:1)
    at Object.get (bundle.js?m=1544431027:1)
    at bundle.js?m=1544431027:1
    at Object.ready (bundle.js?m=1544431027:1)
    at r.value (bundle.js?m=1544431027:1)
    at c.performInitialMount (vendor.js?m=1544431027:1)
    at c.mountComponent (vendor.js?m=1544431027:1)
    at Object.mountComponent (vendor.js?m=1544431027:1)
    at c.performInitialMount (vendor.js?m=1544431027:1)
    at c.mountComponent (vendor.js?m=1544431027:1) in onmatch on 
```

**Comment by svenV88** [comment]
After looking through the code I think the error comes from the import in RegisterComponents.js:
```javascript
import TagField from 'components/TagField';
```
I think it should be:
```javascript
import TagField from '../components/TagField';
```
Because I couldn't find a resolver in the webpack config.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

---

I've re-labelled this as SS4 since there are reports of it happening there as well as SS3

**Comment by wilr** [comment]
Closing as works on latest release
